name = "Delaunator"
uuid = "466f8f70-d5e3-4806-ac0b-a54b75a91218"
authors = ["David Gleich", "Steve Kelly"]
version = "0.1.1"

[compat]
AdaptivePredicates = "1"
Aqua = "0.8"
ExactPredicates = "2"
GeometryBasics = "0.4"
JET = "0.4, 0.7, 0.8"
JSON = "0.21"
Pkg = "1"
StableRNGs = "1"
Test = "1"

julia = "1"

[extras]
AdaptivePredicates = "35492f91-a3bd-45ad-95db-fcad7dcfedb7"
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
ExactPredicates = "429591f6-91af-11e9-00e2-59fbe8cec110"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["AdaptivePredicates", "Aqua", "ExactPredicates", "GeometryBasics", "JET", "JSON", "Pkg", "StableRNGs", "Test"]
